#!/usr/bin/env bash

FILE=${1?Error: project name not given}
LANGUAGE=${2?Error: language you would like to use is not given}
PUB_PRIV=${3?Error: no private or public option given}
cd
python3 /home/david/projects/python/AutomatingProjects/create_github.py $FILE $PUB_PRIV

cd /home/david/projects/$LANGUAGE/
git clone https://github.com/DavidLBallard/$FILE.git

echo "[*]$FILE repository was created and folder was created[*]"
echo "[*]Atom is opening for you[*}]"
cd $FILE
code .
